### ISSUE TITLE
API version should be v2 and not latest (or a parameter)

### ISSUE THREAD

**Issue by jpla-csm** [Cosmo-Tech/azure-platform-deployment-tools#4]
https://github.com/Cosmo-Tech/azure-platform-deployment-tools/blob/8ebe840dc35834cfc322326687d817cff38c6f33/deployment_scripts/v2/deploy_cronjob.sh#L38

**Comment by jpla-csm** [comment]
@jreynard-code @vcarluer pour info, je ne sais pas si vous aviez vu la création de l'issue

**Comment by vcarluer** [comment]
Tu le PR du coup ?

**Comment by jpla-csm** [comment]
pour cette fois ça a été poussé directement.
